ax_state

string[] name

uint16[] Model_Number
uint8[]  Firmware_Version
uint8[]  ID
uint8[]  Baud_Rate
uint8[]  Return_Delay_Time
uint16[] CW_Angle_Limit
uint16[] CCW_Angle_Limit
uint8[]  Temperature_Limit
uint8[]  Min_Voltage_Limit
uint8[]  Max_Voltage_Limit
uint16[] Max_Torque
uint8[]  Status_Return_Level
uint8[]  Alarm_LED
uint8[]  Shutdown

bool[]  Torque_Enable
bool[] LED
uint8[]  CW_Compliance_Margin
uint8[]  CCW_Compliance_Margin
uint8[]  CW_Compliance_Slope
uint8[]  CCW_Compliance_Slope
float[] Goal_Position
float[] Moving_Speed
float[] Torque_Limit
float[] Present_Position
float[] Present_Speed
float[] Present_Load
float[]  Present_Voltage
float[]  Present_Temperature
uint8[]  Registered
bool[]  Moving
uint8[]  Lock
uint16[] Punch